# Generated by Django 4.0.1 on 2022-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mail_pindeposit_profile_uid_profile_wallet_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='profited',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='due_time',
            new_name='date_approved',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='time_now',
            new_name='date_deposited',
        ),
        migrations.RenameField(
            model_name='withdrowal',
            old_name='time_approved',
            new_name='date_approved',
        ),
        migrations.RenameField(
            model_name='withdrowal',
            old_name='time_placed',
            new_name='date_placed',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='sum',
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Money'),
        ),
        migrations.AlterField(
            model_name='pindeposit',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrowal',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Money'),
        ),
    ]
