# Generated by Django 4.0.1 on 2022-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_profited_deposit_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pindeposit',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='withdrowal',
            name='amount',
            field=models.FloatField(),
        ),
    ]
