# Generated by Django 4.0.1 on 2022-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_withdrowal_wallet_address_alter_withdrowal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrowal',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
