# Generated by Django 4.0.1 on 2022-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_withdrowal_date_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='option',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
