# Generated by Django 4.0.1 on 2022-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_deposit_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date_deposited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
