# Generated by Django 4.0.1 on 2022-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_deposit_date_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrowal',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
