# Generated by Django 4.0.1 on 2022-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
