# Generated by Django 4.0.1 on 2022-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_pindeposit_admin_pindeposit_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
