# Generated by Django 4.0.1 on 2022-05-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_referred_profile_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profited',
            field=models.BooleanField(default=False),
        ),
    ]
