# Generated by Django 4.0.1 on 2022-05-18 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='USDT')),
                ('profit', models.DecimalField(decimal_places=3, default=2, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=3, default=2, max_digits=10)),
                ('time_now', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('profited', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
