# Generated by Django 4.0.1 on 2022-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='amount',
            field=models.FloatField(verbose_name='USDT'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trading',
            name='sum',
            field=models.FloatField(),
        ),
    ]
