# Generated by Django 4.0.1 on 2022-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_trading_amount_alter_trading_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
