# Generated by Django 4.0.1 on 2022-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_randuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='randuser',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
