# Generated by Django 4.0.1 on 2022-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userpayevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayevidence',
            name='date_upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
